### ISSUE TITLE
rdwr_phy62x2.py error

### ISSUE THREAD

**Issue by Leopoll** [pvvx/THB2#40]
Прошу помощи. Я, наверно, где-то дико туплю, но знать бы где.

```
C:\Users\Usserr>python3 rdwr_phy62x2.py -p COM3 -e -r wh BOOT_TH05_v17.hex
=========================================================
PHY62x2 Utility version 11.03.24
---------------------------------------------------------
Connecting...
PHY62x2 - Reset Ok
Revision: b'001364c8 6222M005'
FlashID: 1364c8, size: 512 kbytes
PHY62x2 - connected Ok
Traceback (most recent call last):
  File "C:\Users\Usserr\rdwr_phy62x2.py", line 738, in <module>
    main()
  File "C:\Users\Usserr\rdwr_phy62x2.py", line 663, in main
    hp = ParseHexFile(args.filename)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Usserr\rdwr_phy62x2.py", line 56, in ParseHexFile
    taddr = (int(hexstr[3:7],16))
             ^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 16: ''

C:\Users\Usserr>python3 --version
Python 3.12.3
```

**Comment by Leopoll** [comment]
С другого компа заработало. Спасибо за прошивку!
