### ISSUE TITLE
BOOT_TH05D_v17.bin cant be flashed.

### ISSUE THREAD

**Issue by g6094199** [pvvx/THB2#58]
i get this error:

`sudo python3 rdwr_phy62x2.py -p /dev/ttyUSB0 -e -r wh ./update_boot/BOOT_TH05D_v17.bin 

=========================================================
PHY62x2 Utility version 11.03.24
---------------------------------------------------------
Connecting...
PHY62x2 - Reset Ok
Revision: b'001364c8 6222M005'
FlashID: 1364c8, size: 512 kbytes
PHY62x2 - connected Ok
Traceback (most recent call last):
  File "/home/swirthmann/Downloads/THB2-master/rdwr_phy62x2.py", line 738, in <module>
    main()
  File "/home/swirthmann/Downloads/THB2-master/rdwr_phy62x2.py", line 663, in main
    hp = ParseHexFile(args.filename)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/swirthmann/Downloads/THB2-master/rdwr_phy62x2.py", line 43, in ParseHexFile
    for hexstr in fin.readlines():
                  ^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 10: invalid start byte
`

**Comment by g6094199** [comment]
sorry. dont mind. wrong file.
